/* Auto-generated by AuthSystem - 2025-10-27T04:41:26.727Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: '3acde27f-74d3-465e-aaec-94ad46faa881',
  apiKey: 'ak_production_9e1c70fb489556933105666872b05166'
};
